---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodbusers.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDBUser
    plural: mongodbusers
    shortNames:
    - mdbu
    singular: mongodbuser
  additionalPrinterColumns:
    - name: State
      type: string
      description: The current state of the MongoDB User
      JSONPath: .status.phase
    - name: Age
      type: date
      description: The time since the MongoDB User resource was created
      JSONPath: .metadata.creationTimestamp
  validation:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              username:
                type: string
                description: "The username of the user"
              db:
                type: string
                description: "The database the user is stored in"
              project:
                type: string
                description: "The project the user belongs to"
              passwordSecretKeyRef:
                type: object
                properties:
                  name:
                    type: string
                  key:
                    type: string
                description: "DEPRECATED The project the user belongs to"
              mongodbResourceRef:
                properties:
                  name:
                    type: string
                    description: "The name of a MongoDB resource in the same namespace"
              roles:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "The name of the role"
                    db:
                      type: string
                      description: "The db the role can act on"
                    passwordSecretKeyRef:
                      properties:
                        name:
                          type: string
                        key:
                          type: string
                  required:
                    - name
                    - db
            required:
              - username
              - db
