dist: xenial
language: python
os: linux
sudo: required

python:
- "3.6"

env:
- CHANGE_MINIKUBE_NONE_USER=true DISTRO_TYPE=upstream

before_install:
# check-pr needs to be sourced so it can pass the test early.
- source scripts/ci/check-pr $DISTRO_TYPE

install:
- scripts/ci/install-deps $DISTRO_TYPE

before_script:
- eval $(scripts/ci/operators-env) && scripts/ci/verify-operator
- sudo minikube start --memory=4096 --vm-driver=none --kubernetes-version="v1.12.0" --extra-config=apiserver.v=4
- sudo chown -R $USER ${HOME}/.{mini,}kube
- kubectl config use-context minikube
- scripts/ci/install-olm-local

jobs:
  include:
  - name: Scorecard on minikube
    script:
    - scripts/ci/test-ci $DISTRO_TYPE
    # operators-env exports variables containing all operators to be tested.
    - eval $(scripts/ci/operators-env) && scripts/ci/test-pr $DISTRO_TYPE
