site_name: Community operators
repo_name: community-operators
repo_url: https://github.com/operator-framework/community-operators
nav:
    - 'Home': README.md
    - 'Operator':
      - 'Implementation': contributing.md
      - 'Versioning' : operator-versioning.md
      - 'Testing' :
        - 'Explained': testing-operators.md
        - 'Via test suite' : using-current-test-suite.md
      - 'Contribution' : contributing-via-pr.md
      - 'Deployment' : operator-deployment.md
      - 'Continues Integration' : ci.md
theme:
  name: material
  features:
    # - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate

hide:
  - navigation # Hide navigation
  - toc        # Hide table of contents

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.tabbed
  - toc:
      toc_depth: 2