apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: brokeredinfraconfigs.admin.enmasse.io
  labels:
    app: enmasse
spec:
  group: admin.enmasse.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: BrokeredInfraConfig
    listKind: BrokeredInfraConfigList
    singular: brokeredinfraconfig
    plural: brokeredinfraconfigs
    categories:
    - enmasse
  versions:
    - name: v1beta1
      served: true
      storage: true
    - name: v1alpha1
      served: true
      storage: false
  validation:
    openAPIV3Schema:
      type: object
      description: BrokeredInfraConfig defines configuration applied to brokers for an instance of the brokered address space type. This resource is created by the service administrator.
      properties:
        spec:
          type: object
          properties:
            version:
              type: string
            networkPolicy:
              type: object
              properties:
                ingress:
                  type: array
                egress:
                  type: array
            admin:
              type: object
              properties:
                podTemplate:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                    spec:
                      type: object
                      properties:
                        affinity:
                          type: object
                        tolerations:
                          type: array
                          items:
                            type: object
                        priorityClassName:
                          type: string
                        securityContext:
                          type: object
                        containers:
                          type: array
                          items:
                            type: object
                            properties:
                              resources:
                                type: object
                resources:
                  type: object
                  properties:
                    memory:
                      type: string
            broker:
              type: object
              properties:
                podTemplate:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                    spec:
                      type: object
                      properties:
                        affinity:
                          type: object
                        tolerations:
                          type: array
                        priorityClassName:
                          type: string
                        securityContext:
                          type: object
                        resources:
                          type: object
                resources:
                  type: object
                  properties:
                    memory:
                      type: string
                    storage:
                      type: string
                javaOpts:
                  type: string
                addressFullPolicy:
                  type: string
                  enum:
                  - PAGE
                  - BLOCK
                  - FAIL
                  - DROP
                storageClassName:
                  type: string
                updatePersistentVolumeClaim:
                  type: boolean
