apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: standardinfraconfigs.admin.enmasse.io
  labels:
    app: enmasse
spec:
  group: admin.enmasse.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: StandardInfraConfig
    listKind: StandardInfraConfigList
    singular: standardinfraconfig
    plural: standardinfraconfigs
    categories:
    - enmasse
  versions:
    - name: v1beta1
      served: true
      storage: true
    - name: v1alpha1
      served: true
      storage: false
  validation:
    openAPIV3Schema:
      type: object
      description: StandardInfraConfig defines configuration applied to routers and brokers for an instance of the standard address space type. This resource is created by the service administrator.
      properties:
        spec:
          type: object
          properties:
            version:
              type: string
            networkPolicy:
              type: object
              properties:
                ingress:
                  type: array
                egress:
                  type: array
            admin:
              type: object
              properties:
                resources:
                  type: object
                  properties:
                    memory:
                      type: string
                podTemplate:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                    spec:
                      type: object
                      properties:
                        affinity:
                          type: object
                        tolerations:
                          type: array
                          items:
                            type: object
                        priorityClassName:
                          type: string
                        securityContext:
                          type: object
                        containers:
                          type: array
                          items:
                            type: object
                            properties:
                              resources:
                                type: object
            broker:
              type: object
              properties:
                minAvailable:
                  anyOf:
                  - type: integer
                  - type: string
                maxUnavailable:
                  anyOf:
                  - type: integer
                  - type: string
                podTemplate:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                    spec:
                      type: object
                      properties:
                        affinity:
                          type: object
                        tolerations:
                          type: array
                        priorityClassName:
                          type: string
                        securityContext:
                          type: object
                        resources:
                          type: object
                resources:
                  type: object
                  properties:
                    memory:
                      type: string
                    storage:
                      type: string
                javaOpts:
                  type: string
                addressFullPolicy:
                  type: string
                  enum:
                  - PAGE
                  - BLOCK
                  - FAIL
                  - DROP
                storageClassName:
                  type: string
                updatePersistentVolumeClaim:
                  type: boolean
                connectorIdleTimeout:
                  type: integer
                connectorWorkerThreads:
                  type: integer
            router:
              type: object
              properties:
                podTemplate:
                  type: object
                  properties:
                    metadata:
                      type: object
                      properties:
                        labels:
                          type: object
                    spec:
                      type: object
                      properties:
                        affinity:
                          type: object
                        tolerations:
                          type: array
                        priorityClassName:
                          type: string
                        securityContext:
                          type: object
                        resources:
                          type: object
                resources:
                  type: object
                  properties:
                    memory:
                      type: string
                minReplicas:
                  type: integer
                minAvailable:
                  anyOf:
                  - type: integer
                  - type: string
                maxUnavailable:
                  anyOf:
                  - type: integer
                  - type: string
                linkCapacity:
                  type: integer
                idleTimeout:
                  type: integer
                workerThreads:
                  type: integer
                policy:
                  type: object
                  properties:
                    maxConnections:
                      type: integer
                    maxConnectionsPerUser:
                      type: integer
                    maxConnectionsPerHost:
                      type: integer
                    maxSessionsPerConnection:
                      type: integer
                    maxSendersPerConnection:
                      type: integer
                    maxReceiversPerConnection:
                      type: integer
