apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: mongodbreplicasets.mongodb.com
spec:
  group: mongodb.com
  names:
    kind: MongoDbReplicaSet
    listKind: MongoDbReplicaSetList
    plural: mongodbreplicasets
    shortNames:
    - mrs
    singular: mongodbreplicaset
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            members:
              maximum: 50
              minimum: 1
              type: integer
            spec:
              properties:
                credentials:
                  type: string
                project:
                  type: string
                version:
                  type: string
          required:
          - credentials
          - project
          - version
          - members
  version: v1
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: null
  storedVersions: null
