---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: opsmanagers.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDBOpsManager
    plural: opsmanagers
    shortNames:
      - om
    singular: opsmanager
  additionalPrinterColumns:
    - name: Replicas
      type: integer
      description: The number of replicas of MongoDBOpsManager.
      JSONPath: .spec.replicas
    - name: Version
      type: string
      description: The version of MongoDBOpsManager.
      JSONPath: .spec.version
    - name: State (OpsManager)
      type: string
      description: The current state of the MongoDBOpsManager.
      JSONPath: .status.opsManager.phase
    - name: State (AppDB)
      type: string
      description: The current state of the MongoDBOpsManager Application Database.
      JSONPath: .status.applicationDatabase.phase
    - name: State (Backup)
      type: string
      description: The current state of the MongoDBOpsManager Backup Daemon.
      JSONPath: .status.backup.phase
    - name: Age
      type: date
      description: The time since the MongoDBOpsManager resource was created.
      JSONPath: .metadata.creationTimestamp
    - name: Warnings
      type: string
      description: Warnings
      JSONPath: .status.warnings
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            version:
              type: string
            replicas:
              minimum: 1
              type: integer
            clusterName:
              type: string
              format: hostname
              description: "DEPRECATED Use clusterDomain instead"
            clusterDomain:
              type: string
              format: hostname

            security:
              type: object
              properties:
                tls:
                  type: object
                  properties:
                    ca:
                      type: string
                    secretRef:
                      type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name

            adminCredentials:
              type: string
            externalConnectivity:
              type: object
              properties:
                type:
                  type: string
                  enum: ["LoadBalancer", "NodePort"]
                port:
                  type: integer
                loadBalancerIP:
                  type: string
                externalTrafficPolicy:
                  type: string
                  enum: ["Cluster", "Local"]
                annotations:
                  type: object
              required:
                - type
            configuration:
              type: object
            jvmParameters:
              type: array
              items:
                type: string
            statefulSet:
              type: object
              properties:
                spec:
                  type: object
            backup:
              type: object
              properties:
                enabled:
                  type: boolean
                jvmParameters:
                  type: array
                  items:
                    type: string
                headDB:
                  type: object
                  properties:
                    storage:
                      type: string
                    storageClass:
                      type: string
                opLogStores:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mongodbResourceRef:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                          - name
                      mongodbUserRef:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                          - name
                    required:
                      - name
                      - mongodbResourceRef
                blockStores:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mongodbResourceRef:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                          - name
                      mongodbUserRef:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                          - name
                    required:
                      - name
                      - mongodbResourceRef
                s3Stores:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      mongodbResourceRef:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                          - name
                      mongodbUserRef:
                        type: object
                        properties:
                          name:
                            type: string
                        required:
                          - name
                      pathStyleAccessEnabled:
                        type: boolean
                      s3BucketEndpoint:
                        type: string
                      s3BucketName:
                        type: string
                      s3SecretRef:
                        type: object
                        properties:
                          name:
                            type: string
                    required:
                      - name
                      - pathStyleAccessEnabled
                      - s3BucketEndpoint
                      - s3BucketName
                      - s3SecretRef
                statefulSet:
                  type: object
                  properties:
                    spec:
                      type: object
              required:
                - enabled
            applicationDatabase:
              type: object
              properties:
                passwordSecretKeyRef:
                  type: object
                  properties:
                    name:
                      type: string
                    key:
                      type: string
                  required:
                    - name
                security:
                  type: object
                  properties:
                    tls:
                      type: object
                      properties:
                        ca:
                          type: string
                        secretRef:
                          type: object
                          properties:
                            name:
                              type: string
                          required:
                            - name
                      required:
                        - secretRef
                members:
                  maximum: 50
                  minimum: 3
                  type: integer
                version:
                  type: string
                  pattern: "^[0-9]+.[0-9]+.[0-9]+(-.+)?$|^$"
                logLevel:
                  type: string
                  enum: ["DEBUG", "INFO", "WARN", "ERROR", "FATAL"]
                persistent:
                  type: boolean
                statefulSet:
                  type: object
                  properties:
                    spec:
                      type: object

                agent:
                  type: object
                  properties:
                    startupOptions:
                      type: object

                podSpec:
                  type: object
                  properties:
                    podTemplate:
                      type: object
                      properties:
                        metadata:
                          type: object
                        spec:
                          type: object
                    podAntiAffinityTopologyKey:
                      type: string
                    cpu:
                      type: string
                    cpuRequests:
                      type: string
                    memory:
                      type: string
                    memoryRequests:
                      type: string
                    podAffinity:
                      type: object
                    nodeAffinity:
                      type: object
                    persistence:
                      type: object
                      properties:
                        single:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
                        multiple:
                          type: object
                          properties:
                            data:
                              type: object
                              properties:
                                storage:
                                  type: string
                                storageClass:
                                  type: string
                                labelSelector:
                                  type: object
                            journal:
                              type: object
                              properties:
                                storage:
                                  type: string
                                storageClass:
                                  type: string
                                labelSelector:
                                  type: object
                            logs:
                              type: object
                              properties:
                                storage:
                                  type: string
                                storageClass:
                                  type: string
                                labelSelector:
                                  type: object
              required:
                - members
          required:
            - version
            - applicationDatabase
