apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: backupconfigs.jenkins.io
spec:
  group: jenkins.io
  names:
    kind: BackupConfig
    listKind: BackupConfigList
    plural: backupconfigs
    singular: backupconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: BackupConfig is the Schema for the backupconfigs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BackupConfigSpec defines the desired state of BackupConfig
          properties:
            backupOptions:
              description: Options specifies the options provided to user to backup
                between. default BackupConfig sets all to true
              properties:
                config:
                  type: boolean
                jobs:
                  type: boolean
                plugins:
                  type: boolean
              required:
              - config
              - jobs
              - plugins
              type: object
            jenkinsRef:
              description: JenkinsRef points to the Jenkins restore on which Backup
                or Restore will be performed
              type: string
            quietDownDuringBackup:
              description: QuietDownDuringBackup will put the Jenkins instance in
                a QuietDown mode which prevents any new builds from taking place
              type: boolean
            restartAfterRestore:
              description: RestartAfterRestore will restart the Jenkins instance after
                a Restore
              properties:
                enabled:
                  type: boolean
                safe:
                  type: boolean
              required:
              - enabled
              type: object
          required:
          - backupOptions
          - jenkinsRef
          - restartAfterRestore
          type: object
        status:
          description: BackupConfigStatus defines the observed state of BackupConfig
          type: object
      type: object
  version: v1alpha2
  versions:
  - name: v1alpha2
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
