apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: hiveconfigs.hive.openshift.io
spec:
  group: hive.openshift.io
  names:
    kind: HiveConfig
    plural: hiveconfigs
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalCertificateAuthoritiesSecretRef:
              description: AdditionalCertificateAuthoritiesSecretRef is a list of
                references to secrets in the TargetNamespace that contain an additional
                Certificate Authority to use when communicating with target clusters.
                These certificate authorities will be used in addition to any self-signed
                CA generated by each cluster on installation.
              items:
                type: object
              type: array
            backup:
              description: Backup specifies configuration for backup integration.
                If absent, backup integration will be disabled.
              properties:
                minBackupPeriodSeconds:
                  description: MinBackupPeriodSeconds specifies that a minimum of
                    MinBackupPeriodSeconds will occur in between each backup. This
                    is used to rate limit backups. This potentially batches together
                    multiple changes into 1 backup. No backups will be lost as changes
                    that happen during this interval are queued up and will result
                    in a backup happening once the interval has been completed.
                  format: int64
                  type: integer
                velero:
                  description: Velero specifies configuration for the Velero backup
                    integration.
                  properties:
                    enabled:
                      description: Enabled dictates if Velero backup integration is
                        enabled. If not specified, the default is disabled.
                      type: boolean
                  type: object
              type: object
            deprovisionsDisabled:
              description: DeprovisionsDisabled can be set to true to block deprovision
                jobs from running.
              type: boolean
            failedProvisionConfig:
              description: FailedProvisionConfig is used to configure settings related
                to handling provision failures.
              properties:
                skipGatherLogs:
                  description: SkipGatherLogs disables functionality that attempts
                    to gather full logs from the cluster if an installation fails
                    for any reason. The logs will be stored in a persistent volume
                    for up to 7 days.
                  type: boolean
              type: object
            globalPullSecretRef:
              description: GlobalPullSecretRef is used to specify a pull secret that
                will be used globally by all of the cluster deployments. For each
                cluster deployment, the contents of GlobalPullSecret will be merged
                with the specific pull secret for a cluster deployment(if specified),
                with precedence given to the contents of the pull secret for the cluster
                deployment. The global pull secret is assumed to be in the TargetNamespace.
              type: object
            hiveAPIEnabled:
              description: HiveAPIEnabled is a boolean controlling whether or not
                the Hive operator will start up the v1alpha1 aggregated API server.
              type: boolean
            logLevel:
              description: LogLevel is the level of logging to use for the Hive controllers.
                Acceptable levels, from coarsest to finest, are panic, fatal, error,
                warn, info, debug, and trace. The default level is info.
              type: string
            maintenanceMode:
              description: MaintenanceMode can be set to true to disable the hive
                controllers in situations where we need to ensure nothing is running
                that will add or act upon finalizers on Hive types. This should rarely
                be needed. Sets replicas to 0 for the hive-controllers deployment
                to accomplish this.
              type: boolean
            managedDomains:
              description: 'ManagedDomains is the list of DNS domains that are managed
                by the Hive cluster When specifying ''managedDNS: true'' in a ClusterDeployment,
                the ClusterDeployment''s baseDomain should be a direct child of one
                of these domains, otherwise the ClusterDeployment creation will result
                in a validation error.'
              items:
                properties:
                  aws:
                    description: AWS contains AWS-specific settings for external DNS
                    properties:
                      credentialsSecretRef:
                        description: CredentialsSecretRef references a secret in the
                          TargetNamespace that will be used to authenticate with AWS
                          Route53. It will need permission to manage entries for the
                          domain listed in the parent ManageDNSConfig object. Secret
                          should have AWS keys named 'aws_access_key_id' and 'aws_secret_access_key'.
                        type: object
                      region:
                        description: Region is the AWS region to use for route53 operations.
                          This defaults to us-east-1. For AWS China, use cn-northwest-1.
                        type: string
                    type: object
                  domains:
                    description: Domains is the list of domains that hive will be
                      managing entries for with the provided credentials.
                    items:
                      type: string
                    type: array
                  gcp:
                    description: GCP contains GCP-specific settings for external DNS
                    properties:
                      credentialsSecretRef:
                        description: CredentialsSecretRef references a secret in the
                          TargetNamespace that will be used to authenticate with GCP
                          DNS. It will need permission to manage entries in each of
                          the managed domains for this cluster. listed in the parent
                          ManageDNSConfig object. Secret should have a key named 'osServiceAccount.json'.
                          The credentials must specify the project to use.
                        type: object
                    type: object
                type: object
              type: array
            syncSetReapplyInterval:
              description: SyncSetReapplyInterval is a string duration indicating
                how much time must pass before SyncSet resources will be reapplied.
                The default reapply interval is two hours.
              type: string
            targetNamespace:
              description: TargetNamespace is the namespace where the core Hive components
                should be run. Defaults to "hive". Will be created if it does not
                already exist. All resource references in HiveConfig can be assumed
                to be in the TargetNamespace.
              type: string
          type: object
        status:
          properties:
            aggregatorClientCAHash:
              description: AggregatorClientCAHash keeps an md5 hash of the aggregator
                client CA configmap data from the openshift-config-managed namespace.
                When the configmap changes, admission is redeployed.
              type: string
            configApplied:
              description: ConfigApplied will be set by the hive operator to indicate
                whether or not the LastGenerationObserved was successfully reconciled.
              type: boolean
            observedGeneration:
              description: ObservedGeneration will record the most recently processed
                HiveConfig object's generation.
              format: int64
              type: integer
          type: object
  version: v1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
