apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: snapshotconfigurations.zadara.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.state
    description: Status of SnapshotConfiguration
    name: Status
    type: string
  - JSONPath: .spec.appDefinition
    description: AppDefinition name
    name: App
    type: string
  group: zadara.com
  names:
    kind: SnapshotConfiguration
    listKind: SnapshotConfigurationList
    plural: snapshotconfigurations
    singular: snapshotconfiguration
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SnapshotConfiguration allows to select application resources which
        must be included in ApplicationSnapshot (using namespace and labels), and
        to attach Snapshot Policies to the application (including Persistent Volumes
        on VPSA). Additionally, it provides information about all Application Snapshot
        created for this SnapshotConfiguration.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            appDefinition:
              description: Application Definition for the snapshot
              type: string
            policies:
              description: Snapshot policies, defining when ApplicationSnapshots should
                be taken
              items:
                type: string
              minItems: 1
              type: array
          required:
          - appDefinition
          - policies
          type: object
        status:
          properties:
            policies:
              description: All policies mentioned in Spec with lists of all the related
                ApplicationSnapshots
              items:
                properties:
                  name:
                    description: Name of the policy
                    type: string
                  snapshots:
                    description: ApplicationSnapshots which were created from the
                      policy
                    items:
                      properties:
                        name:
                          description: Name of the ApplicationSnapshot
                          type: string
                        state:
                          description: State of the ApplicationSnapshot
                          type: string
                      required:
                      - name
                      - state
                      type: object
                    type: array
                  state:
                    description: 'State of the Snapshot Configuration Policy can be
                      one of the following: Idle - No Application Snapshots using
                      this policy were created. Active - All Application Snapshots
                      using this policy were created successfully. Failed - Some Application
                      Snapshots using this policy are in failed state.'
                    enum:
                    - Idle
                    - Active
                    - Failed
                    type: string
                required:
                - name
                - state
                type: object
              type: array
            state:
              description: 'State of the Snapshot Configuration can be one of the
                following: Pending - Snapshot configuration is waiting for required
                objects to be ready to use. Idle - No Application Snapshots using
                this configuration were created. Active - All Application Snapshots
                using this configuration were created successfully. Failed - Some
                Application Snapshots using this configuration are in failed state.'
              enum:
              - Pending
              - Idle
              - Active
              - Failed
              type: string
          required:
          - state
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
