apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: configs.tf.tungsten.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.replicas
    name: Replicas
    type: integer
  - JSONPath: .status.readyReplicas
    name: Ready_Replicas
    type: integer
  - JSONPath: .status.endpoint
    name: Endpoint
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.active
    name: Active
    type: boolean
  group: tf.tungsten.io
  names:
    kind: Config
    listKind: ConfigList
    plural: configs
    singular: config
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Config is the Schema for the configs API.
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ConfigSpec is the Spec for the Config API.
          properties:
            commonConfiguration:
              description: PodConfiguration is the common services struct.
              properties:
                authParameters:
                  description: AuthParameters auth parameters
                  properties:
                    authMode:
                      description: AuthenticationMode auth mode
                      enum:
                      - noauth
                      - keystone
                      type: string
                    keystoneAuthParameters:
                      description: KeystoneAuthParameters keystone parameters
                      properties:
                        address:
                          type: string
                        adminPassword:
                          type: string
                        adminPort:
                          type: integer
                        adminTenant:
                          type: string
                        adminUsername:
                          type: string
                        authProtocol:
                          type: string
                        insecure:
                          type: boolean
                        port:
                          type: integer
                        projectDomainName:
                          type: string
                        region:
                          type: string
                        userDomainName:
                          type: string
                      type: object
                    keystoneSecretName:
                      type: string
                  type: object
                hostAliases:
                  description: HostAliases is an optional list of hosts and IPs that
                    will be injected into the pod's hosts file if specified.
                  items:
                    description: HostAlias holds the mapping between IP and hostnames
                      that will be injected as an entry in the pod's hosts file.
                    properties:
                      hostnames:
                        description: Hostnames for the above IP address.
                        items:
                          type: string
                        type: array
                      ip:
                        description: IP address of the host file entry.
                        type: string
                    type: object
                  type: array
                hostNetwork:
                  description: Host networking requested for this pod. Use the host's
                    network namespace. If this option is set, the ports that will
                    be used must be specified. Default to false.
                  type: boolean
                imagePullSecrets:
                  description: ImagePullSecrets is an optional list of references
                    to secrets in the same namespace to use for pulling any of the
                    images used by this PodSpec.
                  items:
                    type: string
                  type: array
                logLevel:
                  description: Kubernetes Cluster Configuration
                  enum:
                  - info
                  - debug
                  - warning
                  - error
                  - critical
                  - none
                  type: string
                nodeSelector:
                  additionalProperties:
                    type: string
                  description: 'NodeSelector is a selector which must be true for
                    the pod to fit on a node. Selector which must match a node''s
                    labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/.'
                  type: object
                replicas:
                  description: Number of desired pods. This is a pointer to distinguish
                    between explicit zero and not specified. Defaults to 1.
                  format: int32
                  type: integer
                tolerations:
                  description: If specified, the pod's tolerations.
                  items:
                    description: The pod this Toleration is attached to tolerates
                      any taint that matches the triple <key,value,effect> using the
                      matching operator <operator>.
                    properties:
                      effect:
                        description: Effect indicates the taint effect to match. Empty
                          means match all taint effects. When specified, allowed values
                          are NoSchedule, PreferNoSchedule and NoExecute.
                        type: string
                      key:
                        description: Key is the taint key that the toleration applies
                          to. Empty means match all taint keys. If the key is empty,
                          operator must be Exists; this combination means to match
                          all values and all keys.
                        type: string
                      operator:
                        description: Operator represents a key's relationship to the
                          value. Valid operators are Exists and Equal. Defaults to
                          Equal. Exists is equivalent to wildcard for value, so that
                          a pod can tolerate all taints of a particular category.
                        type: string
                      tolerationSeconds:
                        description: TolerationSeconds represents the period of time
                          the toleration (which must be of effect NoExecute, otherwise
                          this field is ignored) tolerates the taint. By default,
                          it is not set, which means tolerate the taint forever (do
                          not evict). Zero and negative values will be treated as
                          0 (evict immediately) by the system.
                        format: int64
                        type: integer
                      value:
                        description: Value is the taint value the toleration matches
                          to. If the operator is Exists, the value should be empty,
                          otherwise just a regular string.
                        type: string
                    type: object
                  type: array
                tuneSysctl:
                  description: Allow node-init container to tune sysctl options (for
                    all deployers except opneshift it is done by node-init, in openshift
                    - machineconfig)
                  type: boolean
              type: object
            serviceConfiguration:
              description: ConfigConfiguration is the Spec for the Config API.
              properties:
                aaaMode:
                  description: AAAMode aaa mode
                  enum:
                  - noauth
                  - rbac
                  type: string
                analyticsConfigAuditTTL:
                  description: Time (in hours) the analytics config data entering
                    the collector stays in the Cassandra database. Defaults to 2160
                    hours.
                  type: integer
                analyticsDataTTL:
                  description: Time (in hours) that the analytics object and log data
                    stays in the Cassandra database. Defaults to 48 hours.
                  type: integer
                analyticsFlowTTL:
                  description: Time to live (TTL) for flow data in hours. Defaults
                    to 2 hours.
                  type: integer
                analyticsIntrospectPort:
                  type: integer
                analyticsPort:
                  type: integer
                analyticsStatisticsTTL:
                  description: Time to live (TTL) for statistics data in hours. Defaults
                    to 4 hours.
                  type: integer
                apiIntrospectPort:
                  type: integer
                apiPort:
                  type: integer
                cassandraInstance:
                  type: string
                collectorIntrospectPort:
                  type: integer
                collectorPort:
                  type: integer
                containers:
                  items:
                    description: Container defines name, image and command.
                    properties:
                      command:
                        items:
                          type: string
                        type: array
                      image:
                        type: string
                      name:
                        type: string
                    type: object
                  type: array
                deviceManagerIntrospectPort:
                  type: integer
                fabricMgmtIP:
                  type: string
                linklocalServiceConfig:
                  description: LinklocalServiceConfig is the Spec for link local coniguration
                  properties:
                    ip:
                      type: string
                    ipFabricServiceHost:
                      type: string
                    ipFabricServicePort:
                      type: integer
                    name:
                      type: string
                    port:
                      type: integer
                  type: object
                logLevel:
                  type: string
                rabbitmqInstance:
                  type: string
                schemaIntrospectPort:
                  type: integer
                svcMonitorIntrospectPort:
                  type: integer
                useExternalTFTP:
                  type: boolean
                zookeeperInstance:
                  type: string
              type: object
          required:
          - serviceConfiguration
          type: object
        status:
          description: ConfigStatus status of Config
          properties:
            active:
              type: boolean
            configChanged:
              type: boolean
            degraded:
              type: boolean
            endpoint:
              type: string
            nodes:
              additionalProperties:
                type: string
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
