---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mongodb.mongodb.com
spec:
  group: mongodb.com
  version: v1
  scope: Namespaced
  names:
    kind: MongoDB
    plural: mongodb
    shortNames:
      - mdb
    singular: mongodb
  additionalPrinterColumns:
    - name: Type
      type: string
      description: "The type of MongoDB deployment. One of 'ReplicaSet', 'ShardedCluster' and 'Standalone'."
      JSONPath: .spec.type
    - name: State
      type: string
      description: The current state of the MongoDB deployment.
      JSONPath: .status.phase
    - name: Version
      type: string
      description: The version of MongoDB.
      JSONPath: .spec.version
    - name: Age
      type: date
      description: The time since the MongoDB resource was created.
      JSONPath: .metadata.creationTimestamp
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
            - credentials
            - type
            - version
          oneOf:
            - required: [cloudManager]
            - required: [opsManager]
            - required: [project]
          properties:
            type:
              type: string
              enum: ["Standalone", "ReplicaSet", "ShardedCluster"]
            credentials:
              type: string
            project:
              type: string
              description: "DEPRECATED The name of a configMap in the same namespace"
            opsManager:
              type: object
              properties:
                configMapRef:
                  type: object
                  properties:
                    name:
                      type: string
            cloudManager:
              type: object
              properties:
                configMapRef:
                  type: object
                  properties:
                    name:
                      type: string

            version:
              type: string
              pattern: "^[0-9]+.[0-9]+.[0-9]+(-.+)?$"
            logLevel:
              type: string
              enum: ["DEBUG", "INFO", "WARN", "ERROR", "FATAL"]
            persistent:
              type: boolean
            clusterName:
              type: string
              format: hostname
              description: "DEPRECATED Use clusterDomain instead"
            clusterDomain:
              type: string
              format: hostname

            additionalMongodConfig:
              type: object

            exposedExternally:
              type: boolean

            # Generic PodSpec configuration
            podSpec:
              type: object
              properties:
                podTemplate:
                  type: object
                  properties:
                    metadata:
                      type: object
                    spec:
                      type: object
                podAntiAffinityTopologyKey:
                  type: string
                cpu:
                  type: string
                cpuRequests:
                  type: string
                memory:
                  type: string
                memoryRequests:
                  type: string
                podAffinity:
                  type: object
                nodeAffinity:
                  type: object
                persistence:
                  type: object
                  properties:
                    single:
                      type: object
                      properties:
                        storage:
                          type: string
                        storageClass:
                          type: string
                        labelSelector:
                          type: object
                    multiple:
                      type: object
                      properties:
                        data:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
                        journal:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
                        logs:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object

            # TLS & authentication properties
            security:
              type: object
              properties:
                authentication:
                  type: object
                  properties:
                    agents:
                      type: object
                      properties:
                        mode:
                          type: string
                          enum: ["SCRAM", "X509"]
                      required:
                        - mode
                    enabled:
                      type: boolean
                    modes:
                      type: array
                      items:
                        type: string
                        enum: ["SCRAM", "X509", "LDAP"]
                    ignoreUnknownUsers:
                      type: boolean
                tls:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    ca:
                      type: string
                    secretRef:
                      type: object
                      properties:
                        name:
                          type: string
                    additionalCertificateDomains:
                      type: array
                      items:
                        type: string

                ldap:
                  type: object
                  properties:
                    bindQueryUser:
                      type: string
                    servers:
                      type: string
                    transportSecurity:
                      type: string
                      enum: ["none", "tls"]
                    bindQueryPasswordSecretRef:
                      type: object
                      properties:
                        name:
                          type: string
                    caConfigMapRef:
                      type: object

            # Sharded Cluster properties
            shardPodSpec:
              type: object
              properties:
                podTemplate:
                  type: object
                  properties:
                    metadata:
                      type: object
                    spec:
                      type: object
                podAntiAffinityTopologyKey:
                  type: string
                cpu:
                  type: string
                cpuRequests:
                  type: string
                memory:
                  type: string
                memoryRequests:
                  type: string
                podAffinity:
                  type: object
                nodeAffinity:
                  type: object
                persistence:
                  type: object
                  properties:
                    single:
                      type: object
                      properties:
                        storage:
                          type: string
                        storageClass:
                          type: string
                        labelSelector:
                          type: object
                    multiple:
                      type: object
                      properties:
                        data:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
                        journal:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
                        logs:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
            mongosPodSpec:
              type: object
              properties:
                podTemplate:
                  type: object
                  properties:
                    metadata:
                      type: object
                    spec:
                      type: object
                podAntiAffinityTopologyKey:
                  type: string
                cpu:
                  type: string
                cpuRequests:
                  type: string
                memory:
                  type: string
                memoryRequests:
                  type: string
                podAffinity:
                  type: object
                nodeAffinity:
                  type: object
                persistence:
                  type: object
                  properties:
                    single:
                      type: object
                      properties:
                        storage:
                          type: string
                        storageClass:
                          type: string
                        labelSelector:
                          type: object
                    multiple:
                      type: object
                      properties:
                        data:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
                        journal:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
                        logs:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
            configSrvPodSpec:
              type: object
              properties:
                podTemplate:
                  type: object
                  properties:
                    metadata:
                      type: object
                    spec:
                      type: object
                podAntiAffinityTopologyKey:
                  type: string
                cpu:
                  type: string
                cpuRequests:
                  type: string
                memory:
                  type: string
                memoryRequests:
                  type: string
                podAffinity:
                  type: object
                nodeAffinity:
                  type: object
                persistence:
                  type: object
                  properties:
                    single:
                      type: object
                      properties:
                        storage:
                          type: string
                        storageClass:
                          type: string
                        labelSelector:
                          type: object
                    multiple:
                      type: object
                      properties:
                        data:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
                        journal:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
                        logs:
                          type: object
                          properties:
                            storage:
                              type: string
                            storageClass:
                              type: string
                            labelSelector:
                              type: object
            configServerCount:
              minimum: 1
              type: integer
            mongodsPerShardCount:
              minimum: 1
              type: integer
            mongosCount:
              minimum: 1
              type: integer
            shardCount:
              minimum: 1
              type: integer
            mongos:
              type: object
              properties:
                additionalMongodConfig:
                  type: object
            configSrv:
              type: object
              properties:
                additionalMongodConfig:
                  type: object
            shard:
              type: object
              properties:
                additionalMongodConfig:
                  type: object

