apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: plans.capabilities.3scale.net
spec:
  group: capabilities.3scale.net
  names:
    kind: Plan
    listKind: PlanList
    plural: plans
    singular: plan
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            approvalRequired:
              type: boolean
            costs:
              properties:
                costMonth:
                  format: double
                  type: number
                setupFee:
                  format: double
                  type: number
              type: object
            default:
              type: boolean
            limitSelector:
              properties:
                matchExpressions:
                  items:
                    properties:
                      key:
                        type: string
                      operator:
                        type: string
                      values:
                        type: array
                  type: array
                matchLabels:
                  type: object
              type: object
            trialPeriod:
              format: int64
              type: integer
          required:
          - default
          - trialPeriod
          - approvalRequired
          - limitSelector
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
