apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: tackle-operator.v0.0.2
  annotations:
    alm-examples-metadata: >-
      {"tackle-sample":{"description":"Example Tackle CR to deploy Tackle application with all its components"}}
    alm-examples: >-
      [
        {
          "apiVersion": "tackle.io/v1alpha1",
          "kind": "Tackle",
          "metadata": {
            "name": "tackle"
          }
        }
      ]
    capabilities: Basic Install
    categories: Modernization & Migration
    certified: "false"
    containerImage: quay.io/konveyor/tackle-operator:0.0.2-native
    imagePullPolicy: Always
    createdAt: 2021-06-28
    repository: https://github.com/konveyor/tackle-operator
    support: https://github.com/konveyor/tackle-operator/issues
    description: Tackle contains tools that support the modernization and migration of applications to Kubernetes
spec:
  description: >
    Tackle is a collection of tools that supports large-scale application modernization and migration projects to Kubernetes.  
    
    
    Tackle allows users to maintain their portfolio of applications with a full set of metadata and to assess their suitability for modernization leveraging a questionnaire based approach.
    
    
    Tackle is a project within the [Konveyor community](https://www.konveyor.io/).
    
    
    For more information please refer to [Tackle documentation](https://tackle-docs.konveyor.io/).
  version: 0.0.2
  maintainers:
    - email: tackle-dev@googlegroups.com
      name: Tackle by Konveyor community
  maturity: alpha
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAGoAAABoCAYAAAAZ6WWcAAAABHNCSVQICAgIfAhkiAAAABB0RVh0U29mdHdhcmUAU2h1dHRlcmOC0AkAABCySURBVHja7Z17VBx1lse/t6qaV4CQBJAmIQmSyQMI9AOTGDUSE5O4Jms0nkmcrLqTdXX1qDM+5jjOkaRA9+x6Zldnj55xxnH2jHNOHHGdYxwdMxqiyE6UJNA85JGgeW9oSCBAA82ru+7+AWRIoEkXdHf90Nz/oH9VdX/3U/f+7u9ZhCkiFosaxzIyZaYlRJzGhPlgSiZCIjPPABBNROHMLBORl5n7AHQRURszzoG4kRgnmemYl7ievKiprFTbp0r9SVTFbDZ1AUt0M4FXEmg5M2cEvPJEtQw+yKAvSOPPHQ71m6ug/POalSRjIwHrAdgMUMHBwMfsxYeVleoXV0GNkEz7c2lhrGwlie5mZqswhiGqYI3f7SdPYU35C8e+s6Cs1p1rSJbuB2M7AEng5kEDYTd7tTcrKgr2f2dA2WzqRkj0IJg3XfmtBpJmDsDZagqKLgkzBtDmUuDxkr9u9gE0ft3hUD/81oKy5Ki5EuhRMG/xp7w5vh+3Lm9HT5+E/ymKD4pON1ldyF7YjeLyWNQeiwKz38D+qIFfrSxTi781oLKynks1mZQnGHjMn/IxUV6svq4D6ak9IGJ8cyYiqKButLgAAGeawrGvNA7NbSY9xntlYMDzcnX1CyeCbcegtg0Wu/qAKcy0119IAJB+rRsZ17pBxCENLSlJfVi+tFPXNQw8Zgoz7bXY1QeCrZ8SjJtmZ6sLZROeAWMHc2gNHmph5kUS8Btbjnq9dwAvVlWpDVPCo6zWnVtkBX8AYwe+S8LYISv4g9W6c4vwoKz2/GdIkn5nUGdViAEVkqTfWe35zwgZ+hba1fgYYCeDH8NViSbwv9vt6uxOoKChXG0RwqOys9WF0cAv9CQM341IiMeigV9kZ6sLDQdlsagWWcGLALZfRTOmbJcVvGixqBbDQGVn51klhQoAbL7KY1zZLClUkJ2dZw05qKV2dbGiKLv8GQa6KgCYNymKsmupXV0cMlAZGWqSibCLwXdcJaCnzeI7TIRdGRlqUkiyvrAI7ARj21XTT4jWtrAItAF4JKgeZbXn5xHwsKh2IALCwhShWRHwsNWenxc0j7LZ8rcDyBOlwvPnx+P6FWmwWFKQmpqA5OQ4REQMDqhqGqOltQunT7Wirr4RZWUnUVZ2Av39XlFg5dls+ccdjl27AwrKas3LBvHPAJiMrKDJJOO225bi7rtzkL4k2XeYkAiJCTFITIhBTs583HfvSrhcPdi79yvs3l2KRqfRa1rYBMLPrNa8moqK56sCBopk+Vkw0o2s2tq16fjxj25FUtL0CV0fGxuJrVuXYcuWHOzZ48AvX/sUgMvIKqWTLD8L+Nfey1cOeeqPATwVKu3nJPYjdXbfxb/dnljc/8//gAf+aRWioyMm38OXCOnpydi0yYJzTiei5MaLv51vM+HoqchQwso0m3M7nM7i0kmBstnULBB+CSDGCFAxM8zYtP0pLFqcEvDnREaGwb7cBk3zoNX5jVGgAEKW2Zxb5HQWN08462PCkwCSjYgLcfEpuPnOnyA2bmYQs0RC5oq7sPT6LTBQkofsPLH03GJXNxNwvxGaT4tNwA0bf4TwiOiQPG+hdT0W2TYYmQXeb7GrmycESiJ61AilFUXBivUPISIqNqTPzVh+J9IWLTYM1pXsPSYoa456H5jXGKHw32/ZgLiEuQZ0lgmb79mO2NgIY0gxr7HmqPfpAiUxPWiErgsWJGL1upsMe6unxcTgkYdvMc6rxrG7NEam930G32CEog89lAtJMnbR7ObNNiQnxxnjVOAbbDb1+36BIjImgZg7dxZuXrVoUvfo7R2Ao+IUCgsP4U9/qpxgGylh+w9WGJdY+LD/JQsws+x5yxXIpUYo+Mgjt2DHD2/Udc3AgBdlZSdxuOwEystP4cgRJ7xe7eLv27Ytw1NPbgDpXGbqcvVgw20vGTY26IF3RXX58wd9DiEpLG81atvA2jVLdJU/daoVP9zxW7hcvT7LvP32IUiShCefWKfr3rGxkcixp+KLL43ZLqWwvBXAQZ+hjyS62wjFEhJiMHfuLF3XvLfHMS6kYXnrrVL86tfFunXKyZlvXPgbg8NFUJacnXcwc4oRiqWn6x/8+HR/vd9l33ijBIWFh3Tdf8kSs2GgmDnFkrPzjjFBSSzdbpRi83R6U0NDk+6piv986WN8+aX/+9HmzY+HkXI5j5Ghb71RSs2cOU1X+b/+9Wvdz9A0RulB/0HNnDENBsv6UaBsNnUFgLlGaRQZGaarfGnp8Qk9JyN9tq403eBp/blDXEZ4lIRVRmrU1zfgd9n+fg+qvzqjP5RIhGXLUnV5oMdj8NT9CC4SABDTSiP1ae/o8btsa2s3NE3/Vp7Fi82Ii4vyu3xHR8+EnhPQ7G8EF2lo6OI6IxW6cKHL77Jm83T8y0O5up+Re7O+UY+2tm6j26hLuEhZWc+lwqDJwWGpr3fqKr9jx024Z9tyXdesXq2vQ11b1wgBJHmIDyRFUTKM1ubrr5vR3d2n65onnliHdev8U33h965Baqq+dPur6jMigMIwH4mJFhmtjKYxGhqadScHzxfciTVrfC+OiomJwNq16Xj2Wf1dxBMnW4QANcxHAThNBIVKSo7CatXXQ5BlCf/6wl0ID5Px0d6vkJgQg8zMOcjKmgObbR4WLzZDkvQPXrpcvaipOQsxZJCPQkCKCOp8sq8Wjz9+q+6RbkWRkJ9/J37609sRFRUWEF0++6weAwPCrKpNGcr6yCyCQs3NLtTVTewtJkLAIAFA0f46iCODfCQA8aKoVFRkvIFcrl6UlZ0UCNQgHwng6aJo9Mm+Whh9LIVIYW+ojZo+7FFRoqjU3OxCfb2x/Rexwh4wzEcCyCSSVkaGPwHDHob5CHdOXlFRnWHhT7ywN6LfCPCASAo1OtsNC38Chj0M85EAuEX0qqth76K4h9uojqvhDyguPiJo2BvkIwFoEU01I8KfCH04H9Iy3EY5RdQulIZzuXpxuOyEoJwG+UgMnBEVVKjCn7hhDxjmIwF0TEQFG53tqD/S+K3z3gm0UccAQCLmo6KqGAoDdnaKHPaAYT6Kx+OpVUxinnZStK8Ojz269opTH56BPjSdqsaFcyeheTyIip2F5PnZiI67xo9OrrhhDwA8Hk8tMLSbw2ZXz8LgdRO+5Pe/f2Dcwz/OHnegsuQt9LovPTOCiDBv0Upk37QNiinc5/WPP/6WYZsB/GkBHOXq7OH0HAQ6PBXD3+mjpSj9y69HQQIAZsbJIwdw4MP/gub1TM2wN4LL4HIx4i9EBjVW9tfT3Y6Kkt0AGBoDp5vD8LljOt75JAEf/O8MeIc+49Di/AZHHXvHDnvFYoe9kVwGGycNJaJ+SaqxcTD7uzz8Ha/9HJ6BwZVLRQfjUF4/8qiDcPT1y7jrlhZIBHxTvR+L7LdBkpQplO0NcRnpUQ6HWgrg9FQKfy1nG4ZCHOHIidGnrXx9OgL7Sgf34vb3ueFqbRwd9g6fEBnT6SEufwM1JB9PpfDX6x4comxqNaG7d+yTgpytYaPKT5WwdzmPi6A00v4sbOrT6Lvz23zB97znvKS+S5KLqRT2LudxEVRlWcH7RHRGZK8aS5amuTHPPPYq20Xzei5J16dK2COiM5VlBe+PCQoAWON3RVV+v4+toLLMuGt1K8zx/X9LJcI0ZFzrhjl+7DnR4s+Pip3tjcHhkjTIQ95CBfITIip/9mwbjh07h7S0xFG/RYRruGd9C46eikTizH4kzhzAeAtk9+2rFTrsechbePn/LvGo6vLnDxLwkagV+PSzIz5/Cw/TkPW9biTNGh9SW5sbhw4dFxYSAR9dfsbEKFCDjS7eFLUShYWH4Hb3T3JI6gA8Hk3csOfD/qNAORzqOwQ6IGIl2tvdePnlTyZ8fX29E4XvHBLYm+iAw6G+M9ZvytipIb9OjBtErMx7exy4Ni0Bes/FbL3gxjM73xHmSG1fdh8nJI4ttpz8IqPO7PNHfvKP7VDI/y2lfzmUgopagT/jR7TfUbZrra+ffS7A1JhfFTkzcnX26irfoWNDtyHedAV7+wRVWa7uYYibWHR2y/peWCZhITHwZmW5umdCoAYrh5cANIpYuUtHy6e0NA7ZGRMG5XCo1WD8XMTaHT0ViU8Px+l4a1lUd/q5w6FWX6nYFeOH01lcap6duwRApnCjFefCMOCRkDr7yu1V7bEotHUKtjaEUOgoV5/2p6hfuznY6/03AEIONx+sidblWQJJ3ZBd/RK/WuSmppJms3l1B4g2+XtNqD3LoxFSk32fVdHdI+NEY4QorjQApqcrKvL3BRTUUAj8Kil5NQhYLeLr+X/N4ePCmpM4OPR0uilcgGaJ8iscu3R1f3R5R5OzuCQpOfcaAq4TFdZ4bdbcpH6cbgpHR5diICS8VlGu6v7yte4dh/29KADhbVED/8GaaBSXT/fR+WesW9EOIoMyQMLb/b0omMilutub8+eLu+LNubUKKAVASD5mERGuITrKi95+yW/PmhbpHXPicFqkhuNnI3V3mCfPiN4fAPJqqtSTIQEFAOecxS2JiTcdlWQ5GUDQz1K69+/OI9fega4eGU2t/h380Xg+HMsyusZcDt3nkXDibAgTC6IPvB6PWl1RUDPRW0z4tWpuLmm6JjG3niQkBduzVtldCDMxFszpQ3eP5Bcsj5ewcF4PoqNGzz319hNqj4XszNg9mhdqVVVB5WRuMin/b2oqbkpMzK2QJMwEkBW09Pt8OOaZexEZriFtTh+63P55lmWhGzFRo6c1vF4JjiMhGYLa7fUgr6pKnfTc/6QDdXNzcWtMcm5JOBAJYHkwauvqltHabkLmAjeIgAUpveh0y2geB1ZEuIbVOR0Y65ssri4FlQ3B9SgCXukCnq2rUAOysisgeWpDudoC4HGrPf8sgZ8DEPDXtWNE408E3LayDQBQ5cPga67rgCKzT/BBlC4GveAo3/ViIG8aUI2bnMUHkpJWNRDRAgABPbWs3yNhWUY3ZIkvwlqQ0gtZBpwtJni1wawhPs6DjatasWS+7/mn8vpoOFvCggHJwZr2VIUj/zdB8NDAS3a2ulA24RkwdgTyvnetacWiuT1jJg4XOhRMi/RiWuT4C1e8XsJr7yah0y0H2pL/7R3Ai1VVakOQQmnwxGJXH5CJnmbmgKTwsxP6ce/t5yfVYT1cG42iQ4EbxCWio17m/6gsV98Ipi2DGqybnMWOhPgb/yzLkhSIRKPTLWPWdA8SZkzsVKALLgUflMyEx0uBestfGRjwPFpVWfBp8DvMIRJLjporgR4F86Q+emtSGD/YcB7JCfrW93X3SNi9NxGtHUog3OiPGvjVyjK1OHQjGyEWm03dCIkeBPOmicPSsGFlBzLT/DtE/uy5MLz32azJt0tEH0Dj1x0O9cNQ282wFR9W6841JEv3g7EdEzyOLiWpD9cv7cQ8c9+oVJyZ0NRqwuG6aNQdjwRPfHGLBsJu9mpvVlQU7DfKXoYvzcm0P5cWxspWkuhuZrZO1MPMszyYFuWBogDdbgnn20yT8iAiqmCN3+0nT2FN+QuGH5oi1Boqi0VdSTI20uC3k2wGqOBg4GP24sPKSlWoDejCLnaz2dQFLNHNBF5JoOXMHPBPUxBRLYMPMugL0vhzh0MV9sAJcVcljva2OJaRKTMtIeI0JswHUzIREpl5BoBoIgpnZpmIvMzcB6CLiNqYcQ7EjcQ4yUzHvMT15EVNZaXaPlXq//+p6G9Yb1oRUwAAAABJRU5ErkJggg==
      mediatype: image/png
  links:
    - name: Website
      url: https://www.konveyor.io/tackle
    - name: GitHub
      url: https://github.com/konveyor/tackle-operator
    - name: Documentation
      url: https://tackle-docs.konveyor.io/
  customresourcedefinitions:
    owned:
      - name: tackles.tackle.io
        version: v1alpha1
        kind: Tackle
        displayName: Tackle Toolkit
        description: >-
          Create an instance of the Tackle toolkit.  


          To access the Tackle toolkit from the "Developer" perspective, please go to the "Topology" view and click on the "Open URL" icon on the Tackle UI pod.  


          Alternatively from the "Administrator" perspective, please go to Networking->Routes and click on the Location hyperlink.  


          In order to connect with default login credentials, please use "tackle" as username and "password" as password.  
  displayName: Tackle Operator
  provider:
    name: Konveyor
  install:
    spec:
      permissions:
        - rules:
          - apiGroups:
              - ""
            resources:
              - deployments
              - services
              - configmaps
              - secrets
              - persistentvolumeclaims
            verbs:
              - get
              - list
              - create
              - update
              - patch
              - delete
          - apiGroups:
              - tackle.io
            resources:
              - tackles
              - tackles/finalizers
              - tackles/status
            verbs:
              - '*'
          - apiGroups:
              - apps
              - extensions
            resources:
              - deployments
            verbs:
              - '*'
          - apiGroups:
              - networking.k8s.io
            resources:
              - ingresses
            verbs:
              - '*'
          - apiGroups:
              - route.openshift.io
            resources:
              - routes
            verbs:
              - '*'
          serviceAccountName: tackle-operator
      deployments:
        - name: tackle-operator.0.0.2
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: tackle-operator
            template:
              metadata:
                labels:
                  name: tackle-operator
              spec:
                serviceAccountName: tackle-operator
                containers:
                  - name: tackle-operator
                    image: quay.io/konveyor/tackle-operator:0.0.2-native
                    imagePullPolicy: Always
                    env:
                      - name: JAVA_OPERATOR_SDK_CHECK_CRD
                        value: 'false'
                    resources:
                      limits:
                        cpu: 1
                        memory: 200Mi
                      requests:
                        cpu: 100m
                        memory: 50Mi
            strategy:
              type: Recreate
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
  keywords:
    - migration
    - modernization
    - konveyor
    - tackle
  replaces: tackle-operator.v0.0.1
