apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportportals.rp5.reportportal.io
spec:
  group: rp5.reportportal.io
  names:
    kind: ReportPortal
    listKind: ReportPortalList
    plural: reportportals
    singular: reportportal
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          name: ReportPortal
          type: object
        spec:
          description: Specification of the desired behavior of the ReportPortal Operator.
          type: object
          properties:
            app_domain:
              description: Clustser default sub domain hostname for the apps, if specified route will be created with $namespace-reportportal.$app_domain
              type: string
            ui_replicas:
              description: Replicas number for service-ui component
              type: integer
            api_replicas:
              description: Replicas number for service-api component
              type: integer
            ui_image:
              description: service-ui container image url
              type: string
            api_image:
              description: service-api container image url
              type: string
            uat_image:
              description: service-authorization container image url
              type: string
            migration_image:
              description: migrations container image url
              type: string
            analyzer_image:
              description: service-auto-analyzer container image url
              type: string
            index_image:
              description: service-index container image url
              type: string
            index_replicas:
              description: Replicas number for service-index component
              type: integer
            gateway_replicas:
              description: Replicas number for gateway component
              type: integer
            enable_pg_restic_backup:
              description: Whether to enable Postgres backup via restic, yes or no
              type: string
            pg_restic_s3_bucket_init:
              description: Whether to init the Postgres bucket, yes or no
              type: string
            pg_s3_bucket_name:
              description: The s3 Postgres bucket name, need be unique and valid bucket name
              type: string
            pg_restic_password:
              description: The s3 Postgres bucket restic password
              type: string
            es_s3_backup_dir:
              description: The Elasticsearch snapshot path dir, if set the snapshot will be enabled
              type: string
            es_snapshot_bucket:
              description: The Elasticsearch snapshot s3 bucket name
              type: string
            es_backup_schedule:
              description: The Elasticsearch snapshot to s3 bucket schedule, crontab schedule format
              type: string
        status:
          description: Status results of an instance of ReportPortal
          properties:
            conditions:
              description: The resulting conditions when a ReportPortal is instantiated
              items:
                properties:
                  status:
                    type: string
                  type:
                    type: string
                  reason:
                    type: string
                  lastTransitionTime:
                    type: string
                type: object
              type: array
          type: object
  versions:
  - name: v1
    served: true
    storage: true
