name: Auto Assign to Project(s)

on:
  pull_request:
    types: [opened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to Community Operator Submissions
    steps:
    - name: Assign NEW pull requests to project 1
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/operator-framework/community-operators/projects/1'
        column_name: 'To do'