name: Operator test

env:
  OP_TEST_DEBUG: 1
  OP_TEST_CONTAINER_OPT: "-t"
  OP_TEST_SCRIPT_URL: "https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/master/upstream/test/test.sh"
  OP_TEST_IMAGE: "quay.io/operator_testing/operator-test-playbooks:latest"
  # OP_TEST_SCRIPT_URL: "https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/feature/orange-release/upstream/test/test.sh"
  # OP_TEST_IMAGE: "quay.io/operator_testing/operator-test-playbooks:master"
  OP_TEST_PROD: 0
  OP_TEST_DRY_RUN: 0
  # OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
  # OP_TEST_LABELS: "allow/ci-changes allow/operator-version-overwrite"
  # OP_TEST_ADDED_MODIFIED_FILES: "community-operators/aqua/1.0.2/csv.yaml community-operators/aqua/1.0.2/csv1.yaml"
  # OP_TEST_ADDED_MODIFIED_FILES: "upstream-community-operators/aqua/1.0.2/csv.yaml upstream-community-operators/aqua/1.0.2/csv1.yaml"
  # OP_TEST_ADDED_MODIFIED_FILES: "upstream-community-operators/aqua/1.0.2/csv.yaml community-operators/aqua/1.0.2/csv1.yaml"
  # OP_TEST_REMOVED_FILES: ""
  GODEBUG: x509ignoreCN=0

on:
 pull_request:
   types: [opened, reopened, synchronize, unlabeled]
   branches:
     - master

jobs:
  pr-check:
    if: (!contains(github.event.pull_request.labels.*.name, 'needs-ok-to-test'))
    name: "PR-traffic-light"
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install --upgrade pip yq
      - name: Operator test
        id: op-traffic-light
        env:
          OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
          OP_TEST_MODIFIED_FILES: "${{ steps.files.outputs.modified }}"
          OP_TEST_ADDED_MODIFIED_FILES: "${{ steps.files.outputs.added_modified }}"
          OP_TEST_RENAMED_FILES: "${{ steps.files.outputs.renamed }}"
          OP_TEST_REMOVED_FILES: "${{ steps.files.outputs.removed }}"
        run: |
          echo "global labels $OP_TEST_LABELS"
          scripts/ci/actions-env
    outputs:
      op_test_ready: "${{ steps.op-traffic-light.outputs.op_test_ready }}"
      op_release_ready: "${{ steps.op-traffic-light.outputs.op_release_ready }}"
      op_test_stream: "${{ steps.op-traffic-light.outputs.op_test_stream }}"
      op_test_name: "${{ steps.op-traffic-light.outputs.op_test_name }}"
      op_test_version: "${{ steps.op-traffic-light.outputs.op_test_version }}"
      op_test_ci_yaml_only: "${{ steps.op-traffic-light.outputs.op_test_ci_yaml_only }}"

  test-kiwi:
    name: "kiwi / Full operator test"
    needs: pr-check
    if: needs.pr-check.outputs.op_test_ready == '1'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Operator test
        env:
          OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
        run: |
          echo "kiwi ${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"
          scripts/ci/op-test kiwi "${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"

  test-lemon:
    name: "lemon / Deploy from scratch"
    needs: pr-check
    if: needs.pr-check.outputs.op_test_ready == '1' && needs.pr-check.outputs.op_test_stream == 'upstream-community-operators'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Operator test
        env:
          OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
        run: |
          echo "lemon ${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"
          scripts/ci/op-test lemon "${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"

  test-lemon-openshift_4_6:
    name: "lemon / Deploy from scratch (v4.6)"
    needs: pr-check
    if: needs.pr-check.outputs.op_test_ready == '1' && needs.pr-check.outputs.op_test_stream == 'community-operators'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Operator test
        env:
          OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
        run: |
          echo "lemon_v4.6 ${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"
          scripts/ci/op-test lemon_v4.6 "${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"

  test-lemon-openshift_4_7:
    name: "lemon / Deploy from scratch (v4.7)"
    needs: pr-check
    if: needs.pr-check.outputs.op_test_ready == '1' && needs.pr-check.outputs.op_test_stream == 'community-operators'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Operator test
        env:
          OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
        run: |
          echo "lemon_v4.7 ${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"
          scripts/ci/op-test lemon_v4.7 "${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"

  test-lemon-openshift_4_8:
    name: "lemon / Deploy from scratch (v4.8)"
    needs: pr-check
    if: needs.pr-check.outputs.op_test_ready == '1' && needs.pr-check.outputs.op_test_stream == 'community-operators'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Operator test
        env:
          OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
        run: |
          echo "lemon_v4.8 ${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"
          scripts/ci/op-test lemon_v4.8 "${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"

  test-orange-latest:
    name: "orange / Deploy k8s latest"
    needs: pr-check
    if: needs.pr-check.outputs.op_test_ready == '1' && needs.pr-check.outputs.op_test_stream == 'upstream-community-operators'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Operator test
        env:
          OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
        run: |
          echo "orange ${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"
          scripts/ci/op-test orange "${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"

  test-orange-openshift_4_6:
    name: "orange / Deploy o7t v4.6"
    needs: pr-check
    if: needs.pr-check.outputs.op_test_ready == '1' && needs.pr-check.outputs.op_test_stream == 'community-operators'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Operator test
        env:
          OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
        run: |
          echo "orange_v4.6 ${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"
          scripts/ci/op-test orange_v4.6 "${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"

  test-orange-openshift_4_7:
    name: "orange / Deploy o7t v4.7"
    needs: pr-check
    if: needs.pr-check.outputs.op_test_ready == '1' && needs.pr-check.outputs.op_test_stream == 'community-operators'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Operator test
        env:
          OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
        run: |
          echo "orange_v4.7 ${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"
          scripts/ci/op-test orange_v4.7 "${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"

  test-orange-openshift_4_8:
    name: "orange / Deploy o7t v4.8"
    needs: pr-check
    if: needs.pr-check.outputs.op_test_ready == '1' && needs.pr-check.outputs.op_test_stream == 'community-operators'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Operator test
        env:
          OP_TEST_LABELS: "${{ join(github.event.pull_request.labels.*.name, ' ') }}"
        run: |
          echo "orange_v4.8 ${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"
          scripts/ci/op-test orange_v4.8 "${{ needs.pr-check.outputs.op_test_stream }}/${{ needs.pr-check.outputs.op_test_name }}/${{ needs.pr-check.outputs.op_test_version }}"

  test-summary:
    name: "Test summary"
    needs: [ pr-check, test-kiwi, test-lemon, test-lemon-openshift_4_6, test-lemon-openshift_4_7, test-orange-latest, test-orange-openshift_4_6, test-orange-openshift_4_7 ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Summary
        if: needs.pr-check.outputs.op_test_ready == '1'
        continue-on-error: true
        run: |
          echo "This is summary"
