name: prepare-test-index

on:
  repository_dispatch:
    types:
      - manual-test-index
      - index-for-openshift-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check
        run: |
          echo ${{ github.event.client_payload.source_pr }} >> file
          echo
          echo
          cat file
          echo
          echo
          CONTAINER_TOOL=podman OP_DEBUG=2 OP_TOKEN=${{ github.event.client_payload.op_token }} bash <(curl -sL https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/master/upstream/test/osr_run.sh) ${{ github.event.client_payload.source_pr }}
