name: Trigger release pipeline

on:
  schedule:
    - cron: '40 * * * *'

env:
  TRAVIS_TOKEN: ${{ secrets.AUTOMATION_TOKEN_TRAVIS }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger release pipeline
      run: |
        body='{"request": {"branch":"release-pipeline-running"}}'
        curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "$TRAVIS_TOKEN" -d "$body" https://api.travis-ci.com/repo/operator-framework%2Fcommunity-operators/requests
