#TODO: change target Travis repo to operator-framework%2Fcommunity-operators and save secret
name: Trigger release pipeline

on:
  schedule:
    - cron: '0 20 * * *'

env:
  TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger release pipeline
      run: |
        body='{"request": {"branch":"developing-release-pipeline"}}'
        curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "$TRAVIS_TOKEN" -d "$body" https://api.travis-ci.com/repo/J0zi%2Fcommunity-operators/requests
